name: Test & Lint

on:
  push:
    branches: [main]
    paths:
      - "cmd/**"
      - "internal/**"
      - ".github/workflows/test.yml"
      - "go.mod"
      - "go.sum"

  pull_request:
    branches: [main]
    paths:
      - "cmd/**"
      - "internal/**"
      - ".github/workflows/test.yml"
      - "go.mod"
      - "go.sum"

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Run vet
        run: go vet ./...

      - name: Lint (optional)
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout 5m
